/*
THONG TIN NHOM
LOP: ATBMTT_11
MA NHOM: 9
    1712889 _ Le Thi Thanh Tuyen
    1712890 _ Nguyen Thi Thanh Tuyen
    1712895 _ Tran Thi Diem Uyen
    1712896 _ Pham Thi Cam Van
    1712926 _ Luong Tuong Vy
*/

--Nguoi thuc hien: 1712926_Luong Tuong Vy
--------------------------------------TAO USERS---------------------------------------------------------------------------------
--------------------------------------TAO USER ADMIN DUOI QUYEN SYS-------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
   EXECUTE IMMEDIATE 'DROP USER U_ADMIN CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER U_ADMIN IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO U_ADMIN;
GRANT CREATE SESSION TO U_ADMIN;
GRANT ALL PRIVILEGES TO U_ADMIN WITH ADMIN OPTION;

--------------------------------------TAO VA CAP QUYEN TRUY CAP CHO USER DUOI QUYEN ADMIN---------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
   EXECUTE IMMEDIATE 'DROP USER "1000"';
   EXECUTE IMMEDIATE 'DROP USER "1001"';
   EXECUTE IMMEDIATE 'DROP USER "1002"';
   EXECUTE IMMEDIATE 'DROP USER "1003"';
   EXECUTE IMMEDIATE 'DROP USER "1004"';
   EXECUTE IMMEDIATE 'DROP USER "1005"';
   EXECUTE IMMEDIATE 'DROP USER "1006"';
   EXECUTE IMMEDIATE 'DROP USER "1007"';
   EXECUTE IMMEDIATE 'DROP USER "1008"';
   EXECUTE IMMEDIATE 'DROP USER "1009"';
   EXECUTE IMMEDIATE 'DROP USER "1010"';
   EXECUTE IMMEDIATE 'DROP USER "1011"';
   EXECUTE IMMEDIATE 'DROP USER "1012"';
   EXECUTE IMMEDIATE 'DROP USER "1013"';
   EXECUTE IMMEDIATE 'DROP USER "1014"';
   EXECUTE IMMEDIATE 'DROP USER "1015"';
   EXECUTE IMMEDIATE 'DROP USER "1016"';
   EXECUTE IMMEDIATE 'DROP USER "1017"';
   EXECUTE IMMEDIATE 'DROP USER "1018"';
   EXECUTE IMMEDIATE 'DROP USER "1019"';
   EXECUTE IMMEDIATE 'DROP USER "1020"';
   EXECUTE IMMEDIATE 'DROP USER "1021"';
   EXECUTE IMMEDIATE 'DROP USER "1022"';
   EXECUTE IMMEDIATE 'DROP USER "1023"';
   EXECUTE IMMEDIATE 'DROP USER "1024"';
   EXECUTE IMMEDIATE 'DROP USER "1025"';
   EXECUTE IMMEDIATE 'DROP USER "1026"';
   EXECUTE IMMEDIATE 'DROP USER "1027"';
   EXECUTE IMMEDIATE 'DROP USER "1028"';
   EXECUTE IMMEDIATE 'DROP USER "1029"';
   EXECUTE IMMEDIATE 'DROP USER "1030"';
   EXECUTE IMMEDIATE 'DROP USER "1031"';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--CAP QUYEN TRUY CAP CHO USER
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--USER 1000
CREATE USER "1000" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1000";
GRANT CREATE SESSION TO "1000";

--USER 1001
CREATE USER "1001" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1001";
GRANT CREATE SESSION TO "1001";

--USER 1002
CREATE USER "1002" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1002";
GRANT CREATE SESSION TO "1002";

--USER 1003
CREATE USER "1003" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1003";
GRANT CREATE SESSION TO "1003";

--USER 1004
CREATE USER "1004" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1004";
GRANT CREATE SESSION TO "1004";

--USER 1005
CREATE USER "1005" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1005";
GRANT CREATE SESSION TO "1005";

--USER 1006
CREATE USER "1006" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1006";
GRANT CREATE SESSION TO "1006";

--USER 1007
CREATE USER "1007" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1007";
GRANT CREATE SESSION TO "1007";

--USER 1008
CREATE USER "1008" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1008";
GRANT CREATE SESSION TO "1008";

--USER 1009
CREATE USER "1009" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1009";
GRANT CREATE SESSION TO "1009";

--USER 1010
CREATE USER "1010" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1010";
GRANT CREATE SESSION TO "1010";

--USER 1011
CREATE USER "1011" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1011";
GRANT CREATE SESSION TO "1011";

--USER 1012
CREATE USER "1012" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1012";
GRANT CREATE SESSION TO "1012";

--USER 1013
CREATE USER "1013" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1013";
GRANT CREATE SESSION TO "1013";

--USER 1014
CREATE USER "1014" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1014";
GRANT CREATE SESSION TO "1014";

--USER 1015
CREATE USER "1015" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1015";
GRANT CREATE SESSION TO "1015";

--USER 1016
CREATE USER "1016" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1016";
GRANT CREATE SESSION TO "1016";

--USER 1017
CREATE USER "1017" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1017";
GRANT CREATE SESSION TO "1017";

--USER 1018
CREATE USER "1018" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1018";
GRANT CREATE SESSION TO "1018";

--USER 1019
CREATE USER "1019" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1019";
GRANT CREATE SESSION TO "1019";

--USER 1020
CREATE USER "1020" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1020";
GRANT CREATE SESSION TO "1020";

--USER 1021
CREATE USER "1021" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1021";
GRANT CREATE SESSION TO "1021";

--USER 1022
CREATE USER "1022" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1022";
GRANT CREATE SESSION TO "1022";

--USER 1023
CREATE USER "1023" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1023";
GRANT CREATE SESSION TO "1023";

--USER 1024
CREATE USER "1024" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1024";
GRANT CREATE SESSION TO "1024";

--USER 1025
CREATE USER "1025" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1025";
GRANT CREATE SESSION TO "1025";

--USER 1026
CREATE USER "1026" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1026";
GRANT CREATE SESSION TO "1026";

--USER 1027
CREATE USER "1027" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1027";
GRANT CREATE SESSION TO "1027";

--USER 1028
CREATE USER "1028" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1028";
GRANT CREATE SESSION TO "1028";

--USER 1029
CREATE USER "1029" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1029";
GRANT CREATE SESSION TO "1029";

--USER 1030
CREATE USER "1030" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1030";
GRANT CREATE SESSION TO "1030";

--USER 1031
CREATE USER "1031" IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE TO "1031";
GRANT CREATE SESSION TO "1031";



--------------------------------------TAO VA CAP QUYEN CHO ROLE DUOI QUYEN ADMIN------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
   EXECUTE IMMEDIATE 'DROP ROLE RQUANLYCHUYENMON';
   EXECUTE IMMEDIATE 'DROP ROLE RBACSI';
   EXECUTE IMMEDIATE 'DROP ROLE RBOPHANBANTHUOC';
   EXECUTE IMMEDIATE 'DROP ROLE RKETOAN';
   EXECUTE IMMEDIATE 'DROP ROLE QUANLITAINGUYENNHANSU';
   EXECUTE IMMEDIATE 'DROP ROLE BOPHANTIEPTAN';
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIENPHONGTAIVU';
   EXECUTE IMMEDIATE 'DROP ROLE QUANLITAIVU';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE ROLE RQUANLYCHUYENMON;
GRANT  EXEMPT ACCESS POLICY to RQUANLYCHUYENMON;

CREATE ROLE RBACSI;
GRANT  EXEMPT ACCESS POLICY to RBACSI;

CREATE ROLE RBOPHANBANTHUOC;
GRANT  EXEMPT ACCESS POLICY to RBOPHANBANTHUOC;

CREATE ROLE RKETOAN;
GRANT  EXEMPT ACCESS POLICY to RKETOAN;

--GAN ROLE CHO NHOM USERS TUONG UNG
GRANT RQUANLYCHUYENMON TO "1009", "1018";
GRANT RBACSI TO "1000", "1001", "1002", "1003", "1004", "1005", "1006", "1010";
GRANT RBOPHANBANTHUOC TO "1016", "1019", "1028", "1029";
GRANT RKETOAN TO "1011", "1017", "1030", "1031";

--GRANT quyen cho Role RQUANLYCHUYENMON
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
GRANT SELECT ON U_ADMIN.BENHAN TO RQUANLYCHUYENMON;
GRANT SELECT ON U_ADMIN.CHITIETTHUTUC TO RQUANLYCHUYENMON;
GRANT SELECT ON U_ADMIN.BENHNHAN TO RQUANLYCHUYENMON;
GRANT SELECT ON U_ADMIN.TOATHUOC TO RQUANLYCHUYENMON;
GRANT SELECT ON U_ADMIN.CHITIETTHUOCDIEUTRI TO RQUANLYCHUYENMON;

--GRANT quyen cho Role RBACSI
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
GRANT SELECT ON U_ADMIN.THUTUC TO RBACSI;
GRANT SELECT ON U_ADMIN.THUOC TO RBACSI;
GRANT SELECT, UPDATE ON U_ADMIN.BENHAN TO RBACSI;
GRANT SELECT, UPDATE ON U_ADMIN.CHITIETTHUTUC TO RBACSI;
GRANT SELECT, UPDATE ON U_ADMIN.TOATHUOC TO RBACSI;
GRANT SELECT, UPDATE ON U_ADMIN.CHITIETTHUOCDIEUTRI TO RBACSI;

--GRANT quyen cho Role RBOPHANBANTHUOC
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
GRANT SELECT ON U_ADMIN.TOATHUOC TO RBOPHANBANTHUOC;
GRANT SELECT ON U_ADMIN.CHITIETTHUOCDIEUTRI TO RBOPHANBANTHUOC;
GRANT SELECT ON U_ADMIN.THUOC TO RBOPHANBANTHUOC;
GRANT UPDATE (TONGTIEN, DONGIA) ON U_ADMIN.CHITIETTHUOCDIEUTRI TO RBOPHANBANTHUOC;
GRANT UPDATE (TONGTIEN) ON U_ADMIN.TOATHUOC TO RBOPHANBANTHUOC;

--GRANT quyen cho Role RKETOAN
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
GRANT SELECT ON U_ADMIN.NHANVIEN TO RKETOAN;
GRANT SELECT ON U_ADMIN.PHUCAP TO RKETOAN;
GRANT SELECT ON U_ADMIN.CHAMCONG TO RKETOAN;
GRANT INSERT ON U_ADMIN.LUONG TO RKETOAN;

--GRANT quyen cho USER GiamDoc
GRANT SELECT ON U_ADMIN.NHANVIEN TO "1000";

---------------------------------VPD BAC SI CHI DUOC XEM BENH AN DO MINH DIEU TRI-----------------------------------------------
CREATE OR REPLACE FUNCTION SELECT_BENHAN_BACSI (
P_SCHEMA IN VARCHAR2,
P_OBJECT IN VARCHAR2)
RETURN VARCHAR2 
AS
BEGIN
    RETURN 'MABACSI = USER';
END;

--ADD HÀM VÀO CHÍNH SÁCH
BEGIN
DBMS_RLS.ADD_POLICY
(OBJECT_SCHEMA => 'U_ADMIN',
OBJECT_NAME => 'BENHAN',
POLICY_NAME => 'S_BA_BS',
POLICY_FUNCTION => 'SELECT_BENHAN_BACSI',
STATEMENT_TYPES => 'SELECT');
END;

--XOA HAM 
BEGIN
DBMS_RLS.DROP_POLICY
(OBJECT_SCHEMA => 'U_ADMIN',
OBJECT_NAME => 'BENHAN',
POLICY_NAME => 'S_BA_BS');
END;

SELECT * FROM U_ADMIN.BENHAN;

--TAO VIEW CHO PHEP NHAN VIEN DUOC XEM THONG TIN CUA BAN THAN

CREATE OR REPLACE VIEW View_NV_NV AS
SELECT * FROM U_ADMIN.NHANVIEN
WHERE USER = MANV;

CREATE OR REPLACE VIEW View_NV_LUONG AS
SELECT * FROM U_ADMIN.LUONG
WHERE USER = MANV;

CREATE OR REPLACE VIEW View_NV_BS AS
SELECT * FROM U_ADMIN.BACSI
WHERE USER = MANV;

GRANT SELECT ON View_NV_NV TO "1001";
GRANT SELECT ON View_NV_LUONG TO "1001";
GRANT SELECT ON View_NV_BS TO "1001";

SELECT * FROM U_ADMIN.View_NV_NV;
SELECT * FROM U_ADMIN.View_NV_LUONG;
SELECT * FROM U_ADMIN.View_NV_BS;

--Nguoi thuc hien: 1712895_Tran Thi Diem Uyen
--TAO ROLE CHO CAC VITRI 
CREATE ROLE QUANLITAINGUYENNHANSU ;
CREATE ROLE BOPHANTIEPTAN;
CREATE ROLE NHANVIENPHONGTAIVU;
CREATE ROLE QUANLITAIVU;

GRANT CREATE SESSION TO QUANLITAINGUYENNHANSU, BOPHANTIEPTAN, NHANVIENPHONGTAIVU, QUANLITAIVU;

--GRANT QUYEN CHO QUANLITAINGUYENNHANSU 
GRANT SELECT,DELETE,INSERT,UPDATE ON U_ADMIN.PHONGBAN TO QUANLITAINGUYENNHANSU;
GRANT SELECT,DELETE,INSERT,UPDATE ON U_ADMIN.BACSI TO QUANLITAINGUYENNHANSU;
GRANT SELECT,DELETE,INSERT,UPDATE ON U_ADMIN.NHANVIEN TO QUANLITAINGUYENNHANSU;
GRANT SELECT,DELETE,INSERT,UPDATE ON U_ADMIN.CHAMCONG TO QUANLITAINGUYENNHANSU;
GRANT SELECT,DELETE,INSERT,UPDATE ON U_ADMIN.PHUCAP TO QUANLITAINGUYENNHANSU;
GRANT SELECT,DELETE,INSERT,UPDATE ON U_ADMIN.LICHTRUC TO QUANLITAINGUYENNHANSU;
GRANT SELECT ON U_ADMIN.LUONG TO QUANLITAINGUYENNHANSU;

--GRANT QUYEN CHO BOPHANTIEPTAN
GRANT INSERT,DELETE,UPDATE,SELECT ON U_ADMIN.BENHNHAN TO BoPhanTiepTan;
GRANT SELECT,INSERT  (MABENHAN,MABACSI,MABENHNHAN) ON U_ADMIN.BENHAN TO  BoPhanTiepTan;
GRANT SELECT ON U_ADMIN.LICHTRUC TO  BoPhanTiepTan;
GRANT SELECT ON U_ADMIN.PHONG TO  BoPhanTiepTan;

--GRANT QUYEN CHO NHANVIENPHONGTAIVU 
GRANT SELECT,UPDATE (SOTIEN) ON U_ADMIN.CHITIETTHUTUC TO NHANVIENPHONGTAIVU;
GRANT SELECT ON U_ADMIN.CHITIETTHUTUC TO NHANVIENPHONGTAIVU;
GRANT SELECT ON U_ADMIN.THUTUC TO NHANVIENPHONGTAIVU;
GRANT SELECT,INSERT (MABENHAN,MABACSI,MABENHNHAN) ON U_ADMIN.BENHAN TO  NHANVIENPHONGTAIVU;

--GRANT QUYEN CHO QUANLITAIVU
GRANT SELECT,UPDATE ON U_ADMIN.CHITIETTHUTUC TO QUANLITAIVU;
GRANT SELECT,UPDATE ON U_ADMIN.THUTUC TO QUANLITAIVU;
GRANT SELECT ON U_ADMIN.BENHAN TO QUANLITAIVU;
GRANT SELECT ON U_ADMIN.BENHNHAN TO QUANLITAIVU;

--GRANT QUYEN CHO USER
GRANT QUANLITAINGUYENNHANSU TO "1007", "1021";
GRANT BOPHANTIEPTAN TO "1013","1014","1022","1023";
GRANT NHANVIENPHONGTAIVU TO "1012","1020","1026","1027";
GRANT QUANLITAIVU  TO "1008","1015","1024","1025";


CREATE OR REPLACE VIEW U_ADMIN.XEMTHONGTINNHANVIEN_VIEW AS
  SELECT *
  FROM U_ADMIN.NHANVIEN
  WHERE MAPHONGBAN = (SELECT MAPHONGBAN FROM PHONGBAN WHERE TRUONGPHONGBAN = USER );

--XEM THONG TIN NHAN VIEN CUNG PHONG BAN
GRANT SELECT ON U_ADMIN.XEMTHONGTINNHANVIEN_VIEW TO "1007";
GRANT SELECT ON U_ADMIN.XEMTHONGTINNHANVIEN_VIEW TO "1014";
GRANT SELECT ON U_ADMIN.XEMTHONGTINNHANVIEN_VIEW TO "1020";
GRANT SELECT ON U_ADMIN.XEMTHONGTINNHANVIEN_VIEW TO "1016";
GRANT SELECT ON U_ADMIN.XEMTHONGTINNHANVIEN_VIEW TO "1017";
GRANT SELECT ON U_ADMIN.XEMTHONGTINNHANVIEN_VIEW TO "1003";

--CAI DAT POLICY NHAN VIEN XEM DUOC LUONG CUA MINH 
CREATE OR REPLACE FUNCTION U_ADMIN.POLICY_LUONG(P_SCHEMA IN VARCHAR2, P_OBJECT IN VARCHAR2 )
RETURN INT
AS
    USER_CURENT  INT := SYS_CONTEXT ('USERENV', 'SESSION_USER');
BEGIN    
    RETURN 'MaNV = '''|| USER_CURENT  ||''''; 
END;


BEGIN 
DBMS_RLS.ADD_POLICY(
OBJECT_SCHEMA => 'U_ADMIN',
OBJECT_NAME => 'LUONG',
POLICY_NAME => 'POL_2',
FUNCTION_SCHEMA => 'U_ADMIN',
POLICY_FUNCTION => 'POLICY_Luong',
SEC_RELEVANT_COLS => 'LUONG',
SEC_RELEVANT_COLS_OPT => DBMS_RLS.ALL_ROWS);
END;

--XOA HAM 
BEGIN
DBMS_RLS.DROP_POLICY
(OBJECT_SCHEMA => 'U_ADMIN',
OBJECT_NAME => 'LUONG',
POLICY_NAME => 'POL_2');
END;
/

SELECT * FROM ALL_POLICIES;



GRANT EXECUTE ON SYS.DBMS_CRYPTO TO U_ADMIN;

CREATE OR REPLACE PACKAGE hash_security AS

  FUNCTION get_hash (p_username  IN  int,
                     p_password  IN  VARCHAR2)
    RETURN VARCHAR2;
    
  PROCEDURE update_user (p_username  IN  int,
                      p_password  IN  VARCHAR2);
                      

END;
--hash 

--Hash ma??t kha??u trong ba?ng User su?? du?ng ki? thua??t hash (password + salt +username ) (Ma? ho?a )
CREATE OR REPLACE PACKAGE BODY hash_security AS

  FUNCTION get_hash (p_username  IN  int,
                     p_password  IN  VARCHAR2)
    RETURN VARCHAR2 AS
    l_salt VARCHAR2(30) := 'INeedSalt';
  BEGIN

    RETURN DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW( UPPER(p_username) || l_salt || UPPER(p_password)),DBMS_CRYPTO.HASH_SH1);
  END;

  PROCEDURE update_user (p_username  IN int,
                      p_password  IN  VARCHAR2) AS
  BEGIN
    UPDATE  user_nv 
    SET  matkhau = get_hash(p_username, p_password)
    WHERE username = p_username ; 
      
    COMMIT;
  END;
  
END;

exec hash_security.update_user('1000','1234');
exec hash_security.update_user('1001','1234');
exec hash_security.update_user('1002','1234');
exec hash_security.update_user('1003','1234');
exec hash_security.update_user('1004','1234');
exec hash_security.update_user('1005','1234');
exec hash_security.update_user('1006','1234');
exec hash_security.update_user('1007','1234');
exec hash_security.update_user('1008','1234');
exec hash_security.update_user('1009','1234');
exec hash_security.update_user('1010','1234');
exec hash_security.update_user('1011','1234');
exec hash_security.update_user('1012','1234');
exec hash_security.update_user('1013','1234');
exec hash_security.update_user('1014','1234');
exec hash_security.update_user('1015','1234');
exec hash_security.update_user('1016','1234');
exec hash_security.update_user('1017','1234');
exec hash_security.update_user('1018','1234');
exec hash_security.update_user('1019','1234');
exec hash_security.update_user('1020','1234');
exec hash_security.update_user('1021','1234');
exec hash_security.update_user('1022','1234');
exec hash_security.update_user('1023','1234');
exec hash_security.update_user('1024','1234');
exec hash_security.update_user('1025','1234');
exec hash_security.update_user('1026','1234');
exec hash_security.update_user('1027','1234');
exec hash_security.update_user('1028','1234');
exec hash_security.update_user('1029','1234');
exec hash_security.update_user('1030','1234');
exec hash_security.update_user('1031','1234');

--Nguoi thuc hien: 1712896_Pham Thi Cam Van
-----------------------------------------------------AUDIT----------------------------------------------------------------------
--dang nhap bang SYS
    --xem tham so khoi tao ban dau anh huong toi audit
SHOW PARAMETER AUDIT;
    --kich hoat chuc nang giam sat
ALTER SYSTEM SET audit_trail = DB SCOPE = SPFILE;

--cho phep U_ADMIN duoc phep xem thong tin Audit
GRANT EXECUTE ON DBMS_FGA TO U_ADMIN;
GRANT SELECT ON DBA_FGA_AUDIT_TRAIL TO U_ADMIN;
GRANT SELECT ON DBA_AUDIT_TRAIL TO U_ADMIN;
--ghi nhat ky audit cau lenh xem, them, xoa sua tren bang U_ADMIN.PHONGBAN neu thanh cong
AUDIT SELECT, INSERT, UPDATE, DELETE ON U_ADMIN.PHONGBAN WHENEVER SUCCESSFUL;
--ghi nhat ky audit cau lenh them, xoa, sua tren bang U_ADMIN.BACSI, U_ADMIN.NHANVIEN
AUDIT INSERT, UPDATE, DELETE ON U_ADMIN.BACSI;
AUDIT INSERT, UPDATE, DELETE ON U_ADMIN.NHANVIEN;
--ghi nhat ky audit cau lenh them, sua U_ADMIN.THUTUC
AUDIT INSERT, UPDATE ON U_ADMIN.THUTUC;
--ghi nhat ky audit khi update trong bang U_ADMIN.NHANVIEN
AUDIT UPDATE ON U_ADMIN.NHANVIEN;
--ghi nhat ky audit khi xem thong tin trong b?ng U_ADMIN.PHUCAP
AUDIT SELECT ON U_ADMIN.PHUCAP;
--ghi nhat ky audit khi update trong bang U_ADMIN.THUOC
AUDIT INSERT, UPDATE, DELETE ON U_ADMIN.THUOC;

--dang nhap vao user U_ADMIN hoac nhan vien cua he thong, thuc hien cac truy van
SELECT * FROM U_ADMIN.PHONGBAN;
SELECT * FROM U_ADMIN.PHUCAP;
INSERT INTO U_ADMIN.THUOC VALUES (1070,'Eugica',50,'Tri ho',TO_DATE('4-12-2025','mm-dd-yyyy'),TO_DATE('4-12-2020','mm-dd-yyyy'),3000,'Viet Nam');

--xem bang Audit de kiem tra ket qua ghi nhat ky, dang nhap U_ADMIN
SELECT * FROM DBA_AUDIT_TRAIL;

select * from all_policies;




