--INDEX TRÊN THUỘC TÍNH "TÊN SẢN PHẨM" CỦA BẢNG "SẢN PHẨM"
USE TIKI_INDEX
--TÌM SẢN PHẨM THEO TÊN SẢN PHẨM
CREATE PROC USP_TIMSP_INDEX @tenSP NVARCHAR(100)
AS
	BEGIN
		SELECT * FROM SANPHAM WHERE TENSP LIKE @tenSP + '%'
	END
GO

USE TIKI
--TÌM SẢN PHẨM THEO TÊN SẢN PHẨM
CREATE PROC USP_TIMSP @tenSP NVARCHAR(100)
AS
	BEGIN
		SELECT * FROM SANPHAM WHERE TENSP LIKE @tenSP + '%'
	END
GO

USE TIKI_INDEX
EXEC USP_TIMSP_INDEX 'Zeesapinan'

USE TIKI
EXEC USP_TIMSP 'Zeesapinan'

--INDEX TRÊN THUỘC TÍNH "MÃ KHÁCH HÀNG" CỦA BẢNG "THÔNG TIN ĐƠN HÀNG"
USE TIKI_INDEX
--TÌM ĐƠN HÀNG THEO TÊN MÃ KH
CREATE PROC USP_TIMDH_INDEX @makh INT
AS
	BEGIN
		SELECT * FROM dbo.THONGTINDONHANG d
		WHERE d.MAKH = @makh
	END
GO

USE TIKI
--TÌM ĐƠN HÀNG THEO TÊN MÃ KH
CREATE PROC USP_TIMDH @makh INT
AS
	BEGIN
		SELECT * FROM dbo.THONGTINDONHANG d
		WHERE d.MAKH = @makh
	END
GO

USE TIKI_INDEX
EXEC USP_TIMDH_INDEX 996

USE TIKI
EXEC USP_TIMDH 996

