
 CREATE DATABASE PTTK_TH
 GO
 USE PTTK_TH
 GO

   --Tao bang nha cung cap:
CREATE TABLE NHACUNGCAP
( 
     MaNCC INT,
     TenNCC NVARCHAR(50),
     SDT NVARCHAR(15),
     DiaChi NVARCHAR(100),
     PRIMARY KEY (MaNCC)
);

   --Tao bang don nhap hang:
CREATE TABLE DONNHAPHANG
(
     MaDonNhap INT,
     Discount INT,
     NgayLapDonNhap DATE,
     TongTien FLOAT,
     MaNVBanHang INT,
     MaNVQuanLy INT,
     MaNCC INT,
     PRIMARY KEY (MaDonNhap)
);

   --Tao bang CT_DonNhapHang:
CREATE TABLE CT_DONNHAPHANG
(
     MaDonNhap INT,
     MaSP INT,
     DonGia FLOAT,
     SoLuong INT,
     SoTien FLOAT,
     PRIMARY KEY (MaDonNhap,MaSP)
);

   --Tao bang don tra hang:
CREATE TABLE DONTRAHANG
(
     MaDonTra INT,
     Discount INT,
     NgayLapDonTra DATE,
     TongTien FLOAT,
     MaNVBanHang INT,
     MaNCC INT,
     
     PRIMARY KEY (MaDonTra)
);

   --Tao bang CT_DonTraHang:
CREATE TABLE CT_DONTRAHANG
(
     MaDonTra INT,
     MaSP INT,
     DonGia FLOAT,
     SoLuong INT,
     SoTien FLOAT,
     
     PRIMARY KEY (MaDonTra,MaSP)
);

--HOADON, CHITIETDONHANG, SANPHAM
CREATE TABLE HOADON
(
	maHD INT,
	maKH INT,
	trangThai NVARCHAR(50),
	tongCong FLOAT,
	ngayLap DATE,
	maNVGiaoHang INT,
	maNVBanHang INT,
	trangThaiThanhToan NVARCHAR(50),
	hinhThucThanhToan NVARCHAR(50),
	PRIMARY KEY(maHD)
)

CREATE TABLE CHITIEDONHANG
(
	maSP INT,
	maHoaDon INT,
	soLuong INT,
	tongCong FLOAT,
	soLuongTra INT DEFAULT 0,
	ngayTra DATE DEFAULT NULL,
	PRIMARY KEY (maSP,maHoaDon)
)

CREATE TABLE SANPHAM
(
	maSP INT,
	ten NVARCHAR(60),
	loai NVARCHAR(60),
	gia FLOAT,
	PRIMARY KEY (maSP)
)

CREATE TABLE KHACHHANG
    (
      MAKH INT PRIMARY KEY,
      HOTEN NVARCHAR(50),
      GIOITINH NVARCHAR(5),
      SDT CHAR(10),
      EMAIL NVARCHAR(50),
      DIACHI NVARCHAR(100),
    )


CREATE TABLE HOADONTHANHTOANTHE
    (
      MAHD INT PRIMARY KEY,
      MATHE BIGINT,
      XACNHAN NVARCHAR(50),
    )

	--Nhan vien
create table NHANVIEN
(
MaNV int,
HoTen nvarchar(30),
NgaySinh date,
GioiTinh char(3),
DiaChi nvarchar(150),
Loai nvarchar(30),
primary key (MaNV)
)
	--Comment
create table COMMENT
(
MaCMT int,
MaKH int,
MaSP int,
Ngay date,
NoiDung nvarchar(150),
MucDo int,
primary key (MaCMT)
)

	--Thong ke Comment
create table THONGKECOMMENT
(
MaNV int,
MaCMT int,
NgayLap date,
DanhGia nvarchar(10),
primary key (MaNV, MaCMT)
)


CREATE TABLE DOITAC
(
	maDT INT,
	tenDT NVARCHAR(50),
	ngayKiHopDong DATE,
	thoiHan DATE,
	viTriDang NVARCHAR(50),
	PRIMARY KEY(maDT,ngayKiHopDong)
)

CREATE TABLE DANHSACHTTT
(
	maSP INT,
	maDT INT,
	ngayKiHopDong DATE,
	ngayDangTin DATE,
	hanDangTin DATE,
	PRIMARY KEY(maSP,maDT,ngayKiHopDong)
)

CREATE TABLE DANHSACHPTN
(
	maSP INT,
	maKH INT,
	danhDau BIT,
	ngayGui DATE,
	PRIMARY KEY(maSP,maKH)
)

CREATE TABLE TAIKHOAN
(
	maKH INT,
	username VARCHAR(30),
	matKhau VARCHAR(30),
	loaiTaiKhoan VARCHAR(30)
	PRIMARY KEY (username)
)

CREATE TABLE GIOHANG
(
	maKH INT,
	maSP INT,
	soLuong INT,
	tongTien FLOAT,
	PRIMARY KEY (maKH,maSP)
)

CREATE TABLE SODIACHI
(
	maKH INT,
	STT INT,
	hoTEN NVARCHAR(50),
	SDT CHAR(10),
	diaChi NVARCHAR(50),
	phuong NVARCHAR(30),
	quan	NVARCHAR(30),
	tinh NVARCHAR(30),
	PRIMARY KEY (maKH,STT)
)

--Tao khoa ngoai:
ALTER TABLE DONNHAPHANG ADD CONSTRAINT FK_DONNHAPHANG_NHANVIENBH FOREIGN KEY(MaNVBanHang) REFERENCES NHANVIEN(MaNV);
ALTER TABLE DONNHAPHANG ADD CONSTRAINT FK_DONNHAPHANG_NHANVIENQL FOREIGN KEY(MaNVQuanLy) REFERENCES NHANVIEN(MaNV);
ALTER TABLE DONNHAPHANG ADD CONSTRAINT FK_DONNHAPHANG_NHACUNGCAP FOREIGN KEY(MaNCC) REFERENCES NHACUNGCAP(MaNCC);

ALTER TABLE CT_DONNHAPHANG ADD CONSTRAINT FK_CT_DONNHAPHANG_SANPHAM FOREIGN KEY(MaSP) REFERENCES SANPHAM(MaSP);
ALTER TABLE CT_DONNHAPHANG ADD CONSTRAINT FK_CT_DONNHAPHANG_DONNHAPHANG FOREIGN KEY(MaDonNhap) REFERENCES DONNHAPHANG(MaDonNhap);

ALTER TABLE DONTRAHANG ADD CONSTRAINT FK_DONTRAHANG_NHANVIEN FOREIGN KEY(MaNVBanHang) REFERENCES NHANVIEN(MaNV);
ALTER TABLE DONTRAHANG ADD CONSTRAINT FK_DONTRAHANG_NHACUNGCAP FOREIGN KEY(MaNCC) REFERENCES NHACUNGCAP(MaNCC);

ALTER TABLE CT_DONTRAHANG ADD CONSTRAINT FK_CT_DONTRAHANG_SANPHAM FOREIGN KEY(MaSP) REFERENCES SANPHAM(MaSP);
ALTER TABLE CT_DONTRAHANG ADD CONSTRAINT FK_CT_DONTRAHANG_DONTRAHANG FOREIGN KEY(MaDonTra) REFERENCES dbo.DONTRAHANG(MaDonTra);

ALTER TABLE dbo.CHITIEDONHANG ADD CONSTRAINT FK_CHITIETDONHANG_SANPHAM FOREIGN KEY (maSP) REFERENCES dbo.SANPHAM(maSP)
ALTER TABLE dbo.CHITIEDONHANG ADD CONSTRAINT FK_CHITIETDONHANG_HOADON FOREIGN KEY (maHoaDon) REFERENCES dbo.HOADON(maHD)

ALTER TABLE dbo.HOADON ADD CONSTRAINT FK_HOADON_NHANVIENGH FOREIGN KEY(maNVGiaoHang) REFERENCES NHANVIEN(maNV)
ALTER TABLE dbo.HOADON ADD CONSTRAINT FK_HOADON_NHANVIENBH FOREIGN KEY(maNVBanHang) REFERENCES NHANVIEN(maNV)
ALTER TABLE dbo.HOADON ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(maKH) REFERENCES KHACHHANG(maKH)

ALTER TABLE dbo.HOADONTHANHTOANTHE ADD CONSTRAINT FK_HOADONTTTHE_HOADON FOREIGN KEY(MAHD) REFERENCES dbo.HOADON(maHD)

alter table COMMENT ADD CONSTRAINT FK_COMMENT_KHACHHANG foreign key (MaKH) references KHACHHANG (MaKH)
alter table COMMENT ADD	CONSTRAINT FK_COMMENT_SANPHAM foreign key (MaSP) references SANPHAM (MaSP)

alter table THONGKECOMMENT ADD CONSTRAINT FK_TKCOMMENT_NHANVIEN foreign key (MaNV) references NHANVIEN (MaNV)
alter table THONGKECOMMENT ADD 	CONSTRAINT FK_TKCOMMENT_COMMENT foreign key (MaCMT) references COMMENT (MaCMT)

ALTER TABLE dbo.DANHSACHTTT ADD CONSTRAINT FK_DANHSACHTTT_SANPHAM FOREIGN KEY (maSP) REFERENCES dbo.SANPHAM(maSP)
ALTER TABLE dbo.DANHSACHTTT ADD CONSTRAINT FK_DANHSACHTTT_DOITAC FOREIGN KEY (maDT,ngayKiHopDong) REFERENCES dbo.DOITAC(maDT,ngayKiHopDong)

ALTER TABLE dbo.DANHSACHPTN ADD CONSTRAINT FK_DANHSACHPTN_SANPHAM FOREIGN KEY (maSP) REFERENCES dbo.SANPHAM(maSP)
ALTER TABLE dbo.DANHSACHPTN ADD CONSTRAINT FK_DANHSACHPTN_KHACHHANG FOREIGN KEY (maKH) REFERENCES dbo.KHACHHANG(maKH)

ALTER TABLE dbo.TAIKHOAN ADD CONSTRAINT FK_TAIKHOAN_KHACHHANG FOREIGN KEY(maKH) REFERENCES dbo.KHACHHANG(MAKH);

ALTER TABLE dbo.GIOHANG ADD CONSTRAINT FK_GIOHANG_KHACHHANG FOREIGN KEY(maKH) REFERENCES dbo.KHACHHANG(MAKH);
ALTER TABLE dbo.GIOHANG ADD CONSTRAINT FK_GIOHANG_SANPHAM FOREIGN KEY(maSP) REFERENCES dbo.SANPHAM(maSP);

ALTER TABLE dbo.SODIACHI ADD CONSTRAINT FK_SODIACHI_KHACHHANG FOREIGN KEY(maKH) REFERENCES dbo.KHACHHANG(MAKH);
